export default {
    LISTEN_SERVER: "Server running on",
    HOST: "http://localhost:",
    MSG_201: "Creado",
    MSG_204: "Contenido no encontrado",
    MSG_400: "Peticion Invalida",
    MSG_401: "No Autorizado",
    MSG_404: "No encontrado",
    MSG_500: "Error interno del servidor",
    FALIED_LOGIN: "Usuario o contraseña incorrecta",
    STATUS_USER: "Usuario inactivo",
    ERROR: "Error",
    ERROR_TOKEN: "No se pudo generar el token",
    SUCCESFUL_LOGIN: "Inicio de sesión exitoso",
    AUTHORIZATION: "Authorization",
    TOKEN_FAILLED: "No se pudo validar el token",
    NOT_AUTHORIZATION: "Usuario no autorizado",
    EMPTY_FIELD: "Campo requerido",
    SUCCESFUL_REGISTER: "Registro exitoso",
    NOT_FOUND: "No se encontraron registro",
    SUCCESFUL_RESPONSE: "Respuesta exitosa",
    SUCCESFUL_UPDATE: "Actualización exitosa",
    SUCCESFUL_DELETE: "Eliminación exitosa",
    NOT_VALID_ID: "No es un ID valido",
    ID_PRODUCT: "El producto con id:",
    NOT_EXISTS: "no existe",
    ID_USER: "El usuario con id:",
    ROLE_NOT_PERMISSIONS: "Su rol no cumple con los permisos para realizar esta acción"
}